name: Deploy app to Production using SSH

on:
  push:
    branches: [victor]

jobs:
  build:
    name: Deploy to motorshop.tk
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
